//
//  CategoriesModel.swift
//  Unit6HW
//
//  Created by C4Q on 2/14/18.
//  Copyright © 2018 Glo. All rights reserved.
//

import Firebase
import Foundation
import FirebaseAuth
import FirebaseStorage
import FirebaseDatabase

class Decks: NSObject {
    let ref: DatabaseReference
//    let categories: [String : String ]
    let name: String
//    let deckID: String //generated by childByAutoId
    
    init(ref: DatabaseReference, name: String) {
        self.ref = ref
        self.name = name
    }
    
    init(snapShot: DataSnapshot) {
        let value = snapShot.value as? [String: Any]
        self.ref = snapShot.ref
        self.name = value?["name"] as? String ?? ""
        
    }
    
    func toAnyObject() -> [String:Any] {
        return ["name": name]
    }

    
}


